// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package custom_models

// CartInput - параметры метода добавления товара в корзину
type CartInput struct {
	// ID товара, который надо добавить в корзину
	ItemID int `json:"itemID"`
	// Количество товара, которое нужно добавить в корзину
	Quantity int `json:"quantity"`
}

type Mutation struct {
}

type Query struct {
}
